### ISSUE TITLE
update some distro's scripts

### ISSUE THREAD

**Issue by 2Oozbeh** [IsaacSchemm/MultiCD#30]
Hi
Please update script for "antix15" and "slitaz 5-rc3". I can't make multi boot cd with current version for these distros. thank you.

**Comment by libertyernie** [comment]
Both of those distros work for me on the current version of multicd (antiX-15-V_386-full.iso and slitaz-5.0-rc3.iso.)

**Comment by IsaacSchemm** [comment]
Both of those distros work for me on the current version of multicd (antiX-15-V_386-full.iso and slitaz-5.0-rc3.iso.)
