### ISSUE TITLE
slitaz

### ISSUE THREAD

**Issue by eerie** [IsaacSchemm/MultiCD#31]
I'm trying to create a multi boot cd with some mini distro ISOs, but running $./multicd.sh it says:
cp: cannot stat ‘/home/user/multicd/temporary-mountpoints/slitaz/boot/rootfs.gz’: No such file or directory

user@arch:~/multicd$ sudo ./multicd.sh 
Cleaning up - removing symlinks to files in current directory
removed ‘dban.version’
removed ‘ipcop.version’
removed ‘slitaz.version’
removed ‘tinycore.version’
Made a link named dban.iso pointing to dban-2.3.0_i586.iso (version 2.3.0_i586)
Made a link named ipcop.iso pointing to ipcop-2.1.8-install-cd.i486.iso (version 2.1.8)
Made a link named slitaz.iso pointing to slitaz-4.0.iso (version 4.0)
Made a link named tinycore.iso pointing to TinyCore-current.iso (version current)

multicd.sh 20150517
Extracting ISO images with mount; will build multicd.iso; UID 0.

DBAN
IPCop
SliTaz
Tiny Core Linux
Memtest86+

Continuing in 2 seconds - press Ctrl+C to cancel
Copying files for each plugin...
Copying DBAN...
Copying IPCop...
Copying SliTaz...
cp: cannot stat ‘/home/user/multicd/temporary-mountpoints/slitaz/boot/rootfs.gz’: No such file or directory

In facts there is no rootfs.gz in that directory:
user@arch:~/multicd/temporary-mountpoints/slitaz/boot$ ls
bzImage  gpxe  grub  isolinux  rootfs1.gz  rootfs2.gz  rootfs3.gz  rootfs4.gz  vmlinuz-2.6.37-slitaz

**Comment by IsaacSchemm** [comment]
Thanks for the report! I updated the plugin to work with both SliTaz 4.0 and 5.0.
