### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by symbios24** [IsaacSchemm/MultiCD#32]
Hello,Can you Add Support For Android x86 images? eg. android 4.2 android 4.4
thanks

**Comment by IsaacSchemm** [comment]
Do you have a link to where they can be downloaded?

**Comment by symbios24** [comment]
Android 4.0.4
https://android-x86.googlecode.com/files/android-x86-4.0-r1-eeepc.iso

Android 4.2
https://android-x86.googlecode.com/files/android-x86-4.2-20130228.iso

Android 4.3
http://android-x86.googlecode.com/files/android-x86-4.3-20130725.iso

Android 4.4
http://sourceforge.net/projects/android-x86/files/Release%204.4/android-x86-4.4-r3.iso/download

**Comment by symbios24** [comment]
Can you make a version for windows?

**Comment by IsaacSchemm** [comment]
I think multicd might work on Cygwin. There are also some other tools that do the same thing as multicd, I think.

See the latest commit for the new android support.

**Comment by symbios24** [comment]
thanks,i cannot use cygwin is too complicated,it will be nice to make a version for windows since there are not any programs that work correct as multicd, There is xboot that is too old and sardu is not working correct it has many problems
