### ISSUE TITLE
Slax 7.0.8 issue (path and initrd* extension)

### ISSUE THREAD

**Issue by braytac** [IsaacSchemm/MultiCD#33]
Hi, the output when run multicd is:
Continuing in 2 seconds - press Ctrl+C to cancel
Copying files for each plugin...
Copying Slax...
cp: cannot stat  «/media/home1600/isos/MultiCD-master/temporary-mountpoints/slax/boot/vmlinuz»: No such file or directory
I modified the plugin for me and it worked (I broke the conditionals, anyway was temporary)
(I could't attach the diff file by privilegies)

--- slax.sh	2015-10-10 23:56:52.000000000 +0000
+++ slax.sh_spanish	2015-10-21 19:27:20.107653229 +0000
@@ -47,13 +47,14 @@
 			cp -r "${MNT}"/slax/slax "${WORK}"/ #Copy everything
 		fi
 		mkdir -p "${WORK}"/boot/slax
-		cp "${MNT}"/slax/boot/vmlinuz "${WORK}"/boot/slax/vmlinuz
-		if [ -f "${MNT}"/slax/boot/initrd.lz ];then
-			SUFFIX=lz
-		else
-			SUFFIX=gz
-		fi
-		cp "${MNT}"/slax/boot/initrd.$SUFFIX "${WORK}"/boot/slax/initrd.$SUFFIX
+		cp "${MNT}"/slax/slax/boot/vmlinuz "${WORK}"/boot/slax/vmlinuz
+#		if [ -f "${MNT}"/slax/slax/boot/initrfs.lz ];then
+#			SUFFIX=lz
+#		else
+#			SUFFIX=gz
+#		fi
+SUFFIX=img
+		cp "${MNT}"/slax/slax/boot/initrfs.$SUFFIX "${WORK}"/boot/slax/initrfs.$SUFFIX
 		umcdmount slax
 		##########
 		if [ "`ls -1 *.lzm 2> /dev/null;true`" != "" ];then
@@ -71,52 +72,24 @@
 elif [ $1 = writecfg ];then
 #BEGIN SLAX ENTRY#
 if [ -f slax.iso ];then
-	if [ -f "${MNT}"/slax/boot/initrd.lz ];then
-		SUFFIX=lz
-	else
-		SUFFIX=gz
-	fi
-	if [ -f slax.version ] && [ "$(cat slax.version)" != "" ];then
-		SLAXVER=" $(cat slax.version)"
-	else
-		SLAXVER=""
-	fi
-	if [ -f "${WORK}"/slax/base/002-xorg.lzm ];then
+#	if [ -f "${MNT}"/slax/slax/boot/initrfs.lz ];then
+#		SUFFIX=lz
+#	else
+#		SUFFIX=gz
+#	fi
+SUFFIX=img
+#
+#	if [ -f slax.version ] && [ "$(cat slax.version)" != "" ];then
+#		SLAXVER=" $(cat slax.version)"
+#	else
+#		SLAXVER=""
+#	fi
+#	if [ -f "${WORK}"/slax/base/002-xorg.lzm ];then
+
 		echo "LABEL xconf
 		MENU LABEL ^Slax$SLAXVER Graphics mode (KDE)
 		KERNEL /boot/slax/vmlinuz
-		APPEND initrd=/boot/slax/initrd.$SUFFIX ramdisk_size=6666 root=/dev/ram0 rw vga=791 splash=silent quiet autoexec=xconf;telinit~4  changes=/slax/
//////////////////////////////////////////////////////
ETC ETC
//////////////////////////////////////////////////////
>> "${WORK}"/boot/isolinux/isolinux.cfg
-	fi
+		APPEND initrd=/slax/boot/initrfs.img load_ramdisk=1 prompt_ramdisk=0 rw printk.time=0 slax.flags=perch,xmode " >> "${WORK}"/boot/isolinux/isolinux.cfg
 fi
 #END SLAX ENTRY#
 else

Regards ;)

Enrique Cabo

**Comment by libertyernie** [comment]
Thanks for the note! I updated slax.sh to work work Slax 7 and use its existing syslinux.cfg. (It won't work with Slax 6 anymore, though.)
