### ISSUE TITLE
BSD tar support

### ISSUE THREAD

**Issue by blueponies666** [IsaacSchemm/MultiCD#34]
You can use the "bsdtar" command (from libarchive) to extract ISO files. It works just like the "tar" command: 

        bsdtar xf iso-file.iso
        bsdtar xf iso-file.iso -C path/to/directory

Of course, there is a version of bsdtar for Ubuntu and other distributions:

http://packages.ubuntu.com/trusty/bsdtar

**Comment by IsaacSchemm** [comment]
Thanks. I've added support for bsdtar (currently preferred over 7z and other programs, but not over loop-mounting the ISO.) Tested on Debian and PC-BSD.
