### ISSUE TITLE
Support to Kali linux

### ISSUE THREAD

**Issue by pl4g4** [IsaacSchemm/MultiCD#35]
Can you guys add support to Kali linux ? 

Im not sure how the plugins work, but i tried adding a kali plugin and its not working at all. I also tried Linux mint and it wasn't in the list when Extracting ISO images with bsdtar;

I tried .generic, it found the ISO for kali and mint, but didnt work after i had the USB ready.

**Comment by IsaacSchemm** [comment]
Yeah, .generic usually only works with the small ISOs (like Core, SliTaz maybe) where everything is in the initrd file.

Linux Mint you should be able to get it to work by naming the ISO [something].linuxmint.iso or linuxmint-[something].iso.
Kali Linux I can look into adding to the list of supported ISOs.

**Comment by pl4g4** [comment]
I saw that there is a backtrack plugin, and since backtrack was kali previously it might work. I'm not sure. I'll try it .

**Comment by IsaacSchemm** [comment]
I uploaded a kali plugin. It actually just forwards the "mini" Kali ISO to the generic plugin, and the big ones to the Debian plugin.

I did find a problem in the Debian plugin - it's been fixed now.
