### ISSUE TITLE
Mint, Debian Ubuntu, Suse, MANJARO, Fedora

### ISSUE THREAD

**Issue by nobicycle** [IsaacSchemm/MultiCD#43]
Thanks for MultiCD.
I was wondering if the #5 Distro  (distrowatch) might be incorporated into MultiCD? It is Arch based, but the ISO's differ in structure to Arch and I'm not sure how to build a plugin even after looking in  Arch.sh

The main  isos are XFCE, KDE and Net Edition here:

https://manjaro.github.io/download/

The 10 community maintained isos are here:

https://manjaro.github.io/download-community/

Best wishes

**Comment by libertyernie** [comment]
I'll check it out. Shouldn't be too hard to add support for it.

**Comment by IsaacSchemm** [comment]
I added a manjaro plugin. It only supports one version of Manjaro on the disc (not multiple like with Ubuntu or some other distros). Maybe it would be possible to do more than one, but I didn't look into it.
