### ISSUE TITLE
Add boot-repair-disk plugin

### ISSUE THREAD

**Issue by 7sDream** [IsaacSchemm/MultiCD#45]
Nice tool! Thank you!

I want to create a Repair CD, include some tools like WinPE, Clonezilla, Disk Erasure and Boot Repair...

All ISO works prefect(thanks generic plugin) except for the boot-repair-disk ISO, It will stuck in the initramfs busybox shell....

Can you add a boot-repair-disk plugin? Thanks.

You can download ISO files from: https://sourceforge.net/projects/boot-repair-cd/

**Comment by IsaacSchemm** [comment]
I added a plugin (just links to the ubuntu plugin, since boot-repair-disk uses casper.) If it doesn't work, comment here or open a new issue.
