### ISSUE TITLE
DrWeb plugin is outdated.

### ISSUE THREAD

**Issue by IMMZ** [IsaacSchemm/MultiCD#47]
I downloaded some antivirus disks ISOs from the links from MultiCD support images page.
**Minor issue**: Please fix the link to AVG on the website - it's broken now.
**Major issue**: After downloading and
_chmod +x ./multicd.sh_
I run
_./multicd.sh_
and get error about Dr Web Live Disk. I attached a build log file.
The problem is it can't find _vmlinuz_ file and it is really absent on that path as I see.
Here's [link from official website](https://download.geo.drweb.com/pub/drweb/livedisk/drweb-livedisk-900-cd.iso) I downloaded an ISO
[build log](https://github.com/IsaacSchemm/MultiCD/files/669673/build.txt)
Without DrWeb the multiboot cd is created without any errors. I looked at plugin and ISO file contents - it seems that plugin should be modified or rewritten. DrWeb now has only elf.img in the %mounted%/boot dir.
XUbuntu x64 14.04.5
MultiCD repository version at 22 December 2016

**Comment by IsaacSchemm** [comment]
Thanks. I fixed the plugin by making the script treat it as a version of Ubuntu.
