### ISSUE TITLE
Wrong codepage for the date.

### ISSUE THREAD

**Issue by IMMZ** [IsaacSchemm/MultiCD#49]
I've created a mutliboot iso in Russian Xubuntu 14.04 and the month name is shown incorrectly on created iso. It seems like encoding problem. It would be nice to get it work automatically or add an option to multicd.sh to choose an encoding.
![Bug's screenshot](https://cloud.githubusercontent.com/assets/1856709/21530941/d006b25e-cd5d-11e6-8e20-d3f3a0b3a9d5.png)

**Comment by IsaacSchemm** [comment]
That's odd - the code that grabs the date sets LANG=C before running the date command, which (at least on this Russian VM I just set up) makes it print the date in English.
Do you know if there's a way to show Cyrillic text correctly in the isolinux boot menu?

**Comment by IMMZ** [comment]
@IsaacSchemm Yes. I've found out this. You need 3 steps to do that:

1. Download [cyr_a8x16.psf Font File](https://yadi.sk/d/MOE6FYUDAofwW)
2. Add **FONT cyr_a8x16.psf** to isolinux.cfg
3. Convert isolinux.cfg to CP866 (I used iconv for that)

After these steps I tested my new ISO - All shown well both Russian and English characters.
![New screenshot](https://cloud.githubusercontent.com/assets/1856709/21552057/55a5cfca-ce18-11e6-942d-bd16b457a473.png)


* I would be glad to create a pull request if you can write detaily how it should behavior (where is the font should be stored, some other details) or you can try it out yourself.

* 'date' command outputs month name in Russian on my OS.

**Comment by IsaacSchemm** [comment]
I've added a feature that checks for Cyrillic text in isolinux.cfg (and any other .cfg files in that folder). If it finds some, it converts the file to CP866 and adds the .psf file (which it looks for at /usr/share/consolefonts/Cyr_a8x16.psf.gz in case you have console-data installed, and in the current directory if you don't.)

Let me know if it doesn't work for you or causes other problems.

**Comment by IMMZ** [comment]
Works well! Thanks!
