### ISSUE TITLE
ArchLinux 2017.01.01 doesen't boot.

### ISSUE THREAD

**Issue by LordJust** [IsaacSchemm/MultiCD#51]
Please fix this probleme:
![issue](https://cloud.githubusercontent.com/assets/25131565/21961710/bce8b138-db11-11e6-9959-0b24a581e9d8.JPG)
I think it is the arch plugin.

Thanks Lord

**Comment by IsaacSchemm** [comment]
What's the label/name of the CD/DVD? The default is "MultiCD" but if you want to change it you can use the -i option of multicd.sh.
If you're using a USB and it has a different label, you'll need to update /arch/boot/syslinux/syslinux.cfg to use it instead of "MultiCD".

**Comment by LordJust** [comment]
It was in VirtualBox using the original ISO created by the Skript. Furthermore Linux Mint works.

**Comment by IsaacSchemm** [comment]
Can you post the URL that you downloaded Arch 2017.01.01 from?

**Comment by LordJust** [comment]
The URL: https://wiki.archlinux.de/title/Download

**Comment by LordJust** [comment]
I edited the plugin. Now it works.
[arch.zip](https://github.com/IsaacSchemm/MultiCD/files/709159/arch.zip)
