### ISSUE TITLE
Freedos ISO Issue

### ISSUE THREAD

**Issue by seriousramius** [IsaacSchemm/MultiCD#52]
Hi, i have a problem with including the freedos-iso (CDROM Standard Installer or Legacy).
I made a symlink pointing to the iso-image for freedos and also for the rest of the iso-images (UBCD,Finnix,..). If the script tries to "stat" the location i get the following error:
Continuing in 2 seconds - press Ctrl+C to cancel
Copying files for each plugin...
Copying Finnix...
Copying FreeDOS...
cp: Aufruf von stat für '/home/benutzer/skripte/MultiCD/temporary-mountpoints/freedos/freedos' nicht möglich: Datei oder Verzeichnis nicht gefunden

Can you please tell me, if you have an idea, what's the reason behind this issue ?
Regards 
Ramius

**Comment by IsaacSchemm** [comment]
The FreeDOS plugin in MultiCD is for FreeDOS 1.1. I'll need to update it to get it to work with 1.2.

**Comment by seriousramius** [comment]
Thanks, for your fast commit. I made the update and got a new error (the script is always executed with sudo:
benutzer@ESPRIMO:~/skripte/MultiCD$ sudo ./multicd.sh -v -t
Cleaning up - removing symlinks to files in current directory
Made a link named 1_ubcd.iso pointing to ubcd.iso (version )

multicd.sh 20161230
Extracting ISO images with mount; will build multicd.iso; UID 0.

Finnix
FreeDOS
GRML
Hiren's BootCD
Trinity Rescue Kit
Ultimate Boot CD
Ubuntu alternate installer
Memtest86+

Continuing in 2 seconds - press Ctrl+C to cancel
Copying files for each plugin...
Copying Finnix...
Copying FreeDOS...
cp: Aufruf von stat für '/home/benutzer/skripte/MultiCD/temporary-mountpoints/freedos/DATA/FDBOOT.IMG' nicht möglich: Datei oder Verzeichnis nicht gefunden

**Comment by libertyernie** [comment]
Are you using the FD12LGCY.iso? That doesn't seem to work for me when I boot the boot image from isolinux. Try FD12CD.iso if you haven't yet.

**Comment by IsaacSchemm** [comment]
Are you using the FD12LGCY.iso? That doesn't seem to work for me when I boot the boot image from isolinux. Try FD12CD.iso if you haven't yet.

**Comment by seriousramius** [comment]
Sorry for my late repy, i was offline during sickness. I used the FD12.iso

**Comment by IsaacSchemm** [comment]
I guess the FDBOOT.img has a lowercase extension this time.

Next time there's a new FreeDOS version I want to test it with all the ISO extraction tools, on both linux and cygwin.

**Comment by seriousramius** [comment]
Yes, it was the lower extension. Thanks, for fast reaction. Is it possible to contribute a donation to your project ?

**Comment by IsaacSchemm** [comment]
Thanks for the offer, but I don't take donations - there are hardly any costs associated with the project :)

**Comment by seriousramius** [comment]
OK ;)
