### ISSUE TITLE
manjaro 17.0.1 xfce boot failed

### ISSUE THREAD

**Issue by braytac** [IsaacSchemm/MultiCD#53]
Greetings! :)
Please, update manjaro plugin for the new boot structure of manjaro 17.0.1 live iso (with grub).
This screenshoot is from multicd.iso with manjaro-xfce-17.0.1-stable-x86_64.iso (and linuxmint....)

![captura de pantalla_2017-05-26_01-50-09](https://cloud.githubusercontent.com/assets/281559/26481217/dbc0e44e-41b5-11e7-9176-450d0a8b4116.png)
![captura de pantalla_2017-05-26_01-50-26](https://cloud.githubusercontent.com/assets/281559/26481218/dbc1f7c6-41b5-11e7-81e9-5b443a3aaa55.png)

Thanks a lot!

**Comment by IsaacSchemm** [comment]
This should fix it (without breaking it if someone uses an older version.)

**Comment by braytac** [comment]
Sorry!! My bad. I was using a slightly older version. Thanks!! ^.^
Run fine :)
