### ISSUE TITLE
Breaks under Ubuntu 16.10 Desktop

### ISSUE THREAD

**Issue by stheno** [IsaacSchemm/MultiCD#55]
Due to a symlink bug in 16.X that I reported a long while back on Ubuntu's stack exchange, the symlink portion of this script seems to die at the point of trying to link. I had to use a 14.04 desktop to generate the multi-iso.

**Comment by IsaacSchemm** [comment]
It works for me on Ubuntu 16.10 (desktop version). What error do you get, if any?

**Comment by stheno** [comment]
error is multiple of these for every script
/home/amd/iso/functions.sh: line 62: /home/amd/iso/plugins/zorin.sh: Permission denied

**Comment by IsaacSchemm** [comment]
Can you try running

    chmod +x plugins/*.sh

and try again?

**Comment by stheno** [comment]
I chmod 0777 the entire folder. No avail.

**Comment by IsaacSchemm** [comment]
I just thought of this - could you try booting from a Ubuntu 16.10 live DVD/USB and try running multicd? (Of course you'll want to mount your hard drive and run multicd from there.)

**Comment by stheno** [comment]
This reply totally got by me. I have gotten quite behind in my work lately and have had zero chance to open up this code. The bugs I had in 16.10 were from full installs in everything related to links. Multiple systems multiple installs. I don't think it was a issue with multicd at all. But more of a distro bug. I'll leave this open until either you close it or I test further as you suggested. But I suspect a raw 16.10 live CD would do the same.

**Comment by IsaacSchemm** [comment]
OK. You can reopen this if it turns out to be a multicd issue.
