### ISSUE TITLE
Filename pattern ubuntu-{something}-*.iso doesn't work with ubuntu plugin

### ISSUE THREAD

**Issue by philipzae** [IsaacSchemm/MultiCD#60]
When i ran the script with ubuntu-mate-16.04-desktop-amd64.iso in the folder, it didnt pick it up, though it did create a mate.amd64.16.04.ubuntu.title file.

**Comment by stheno** [comment]
I had a few hard drives die on me. Sadly one that had all my work from here.
Slowly recovering from that. I'll take a look at this and see about what it is needing.

**Comment by IsaacSchemm** [comment]
Thanks stheno.

In the meantime, you could rename the ISO to something like "mateubuntu-16.04-desktop-amd64.iso" and it will work. You could also use the "casper" plugin my naming it [something].casper.iso.

**Comment by philipzae** [comment]
Before reporting the bug, i had tested renaming it to various things like mate.ubuntu.iso ([supported distributions webpage](https://multicd.us/supported.html) mentioned *.ubuntu.iso would work), ubuntu-mate-16.04-amd64.iso, ubuntu-mate-16.04.iso, and ubuntu-mate.iso, but they all failed. I had also tried symlinking it as mate.ubuntu.iso and ubuntu.iso which also failed.

@IsaacSchemm thanks for the suggestion, as that did work.

**Comment by IsaacSchemm** [comment]
@philipzae I need to update the website :)

**Comment by philipzae** [comment]
I checked and the updated bug title likely needs to be amended, as ubuntu gnome and ubuntu budgie isos also dont work.

ubuntu-budgie-17.04-desktop-i386.iso
ubuntu-gnome-17.04-desktop-amd64.iso

**Comment by IsaacSchemm** [comment]
I pushed a commit that I hope will fix it. Let me know if it works.

**Comment by philipzae** [comment]
Commit does work for ubuntu-{something}-*.iso. Should a separate bug report be opened for mate.ubuntu.com?

**Comment by IsaacSchemm** [comment]
Do you mean mate.ubuntu.iso?
With the way the new plugin is, I might just ask people to use *.casper.iso instead in situations like that. The casper plugin is actually the old ubuntu plugin.

**Comment by philipzae** [comment]
Yes sorry i did mean .iso, but i see that you changed the instructions on the 'Supported Distributions' webpage to no longer state that, so i guess this has been settled. Thanks again for the patch.
