### ISSUE TITLE
Debian 9 Not Working

### ISSUE THREAD

**Issue by rathb5** [IsaacSchemm/MultiCD#62]
Hi

Many Thanks Thanks For MultiCD. Very Handy tool For dual distro Discs.

The Debian plugins Do not work with Debian 9. Seems The ISO has a Different Directory Structure than Debian 8. Is There something I can Change/add to the plugin to get it to work With 9.

Maybe a Updated Plugin Can get generated.

Thanks
Rathb5

**Comment by IsaacSchemm** [comment]
Is it the live CD, or the installer? Hopefully I can take a look at it this
week.

**Comment by rathb5** [comment]
Hi Yes It Is the Live ISOs.  Many Thanks

**Comment by IsaacSchemm** [comment]
Check and see if it works for you now. The path to the isolinux cfg file changed.

**Comment by rathb5** [comment]
Yes That seems to have done the trick. Many thanks again
