### ISSUE TITLE
Multiple iso`s not working 

### ISSUE THREAD

**Issue by symbios24** [IsaacSchemm/MultiCD#68]
Hello i tested your latest script version dated almost a year back all is tested with latest versions of the supported  distributions.

not working: comodo rescue disc does not boot
not working: Drweb rescue disc does not boot
Hirens boot cd shows a warning about no BootCD.txt in hirens.iso
not working: bitdefender rescue disc does not boot
latest kaspersky rescue disc upon the multiboot iso creation stops/hangs the process with this error message: cp: cannot stat /multicd/temporary-mountpoints/kav/boot/rescue: No such file or directory

**Comment by symbios24** [comment]
any change that you fix those issues?

**Comment by libertyernie** [comment]
Can you try kaspersky and hiren's again? I think I fixed them.

Comodo and Drweb worked for me. Do you have links to the versions you are using?

**Comment by symbios24** [comment]
Both comodo and Drweb all the latest versions downloaded from the official site.

http://download.comodo.com/crd/download/setups/comodo_rescue_disk_2.0.261647.1.iso

http://download.geo.drweb.com/pub/drweb/livedisk/drweb-livedisk-900-cd.iso

kaspersky is the last version released in 2018 

thanks

**Comment by symbios24** [comment]
Both comodo and Drweb all the latest versions downloaded from the official site.

http://download.comodo.com/crd/download/setups/comodo_rescue_disk_2.0.261647.1.iso

http://download.geo.drweb.com/pub/drweb/livedisk/drweb-livedisk-900-cd.iso

kaspersky is the last version released in 2018

 i will try them and l,et you know.

thanks

**Comment by libertyernie** [comment]
Comodo and Drweb both work for me. What OS are you using (e.g. Debian, Fedora, Ubuntu, etc)?

**Comment by symbios24** [comment]
i tried both debian 9 and ubuntu 14.04 and got the same result.

**Comment by dv8472** [comment]
latest SystemRescueCd "systemrescuecd-6.0.2.iso" affected too:
{
Copying SystemRescueCd...
cp: cannot stat '.../multicd/temporary-mountpoints/sysrcd/sysrcd.*': No such file or directory
}

**Comment by IsaacSchemm** [comment]
538b2e38cb0d17924567301c64746820c3643c54 should fix SystemRescueCd. You'll have to use "sysresccd.iso" instead of "sysrcd.iso", though.

If it still doesn't work, just open a new issue.

**Comment by dv8472** [comment]
> [538b2e3](https://github.com/IsaacSchemm/MultiCD/commit/538b2e38cb0d17924567301c64746820c3643c54) should fix SystemRescueCd. You'll have to use "sysresccd.iso" instead of "sysrcd.iso", though.
> 
> If it still doesn't work, just open a new issue.

Thanks, it works fine.
Pls update the "documentation" https://multicd.us/supported.html too.
