### ISSUE TITLE
Issue with PDF.js reader.

### ISSUE THREAD

**Issue by Peacock365** [IsaacSchemm/MultiCD#71]
Hi IsaacSchemm,

I found an issue / bug in your PDF.js reader fork for SeaMonkey:

- https://github.com/IsaacSchemm/pdf.js-seamonkey

It doesn't show scrollbars when using it in Pale Moon 28, on macOS. The scrollingitsself is flawless, though. Without the scrollbar, however, you have little idea where you are in the document. I know that the add-on is meant specifically for SeaMonkey, but since Pale Moon is derived from Gecko 52 too, it could likely still be fixed (hopefully).

Pale Moon 28.3.0 (got it from here: https://forum.palemoon.org/viewtopic.php?f=41&t=21295 ), macOS 10.14 Mojave, PDF Viewer 2.0.961 if that matters.

I also know that it is off-topic to post this issue here, but your PDF.js fork repo has no issue section, and there is know other way to reach you on GitHub other than to post the issue in some other repo of yours.

Have a nice day.

Peacock365

**Comment by libertyernie** [comment]
Is it just macOS that has that problem? I tried it quick on Windows and it seemed OK. Or is it on specific PDF files?

**Comment by Peacock365** [comment]
> Is it just macOS that has that problem? I tried it quick on Windows and it seemed OK. Or is it on specific PDF files?

Yes, seems to be specific to macOS. The same PDF.js version in Pale Moon 28.3.0 on Windows 8.1 does show scrollbars.

**Comment by libertyernie** [comment]
Unfortunately I don't have access to macOS on a regular basis. But if someone else can fix it, I'd welcome a pull request :)

**Comment by IsaacSchemm** [comment]
Migrated to https://github.com/IsaacSchemm/pdf.js-seamonkey/issues/4
