### ISSUE TITLE
Request: ReactOS support

### ISSUE THREAD

**Issue by qyot27** [IsaacSchemm/MultiCD#72]
https://reactos.org/

It may or may not be similar to the existing support for Windows discs.  Hopefully there's not much of hitch in name parsing between release ISOs and the per-revision ISOs (although since they've moved to a roughly 3-month release cycle, the per-revision ones may not be as important for something like MultiCD).

**Comment by IsaacSchemm** [comment]
700e4eb956a32e277ceee77e268f7fcddff8bff4

I added a reactos plugin. Use either the original ISO names or "reactos.iso" - you can only have one per disc. Let me know if it doesn't work.
