### ISSUE TITLE
Update sysresccd.iso in https://multicd.us/supported.html

### ISSUE THREAD

**Issue by kiat-huang** [IsaacSchemm/MultiCD#76]
Because the doc hasn't been updated with the developers correct advice buried within this thread, I just wasted over 30 minutes and lost some grey cells trying to solve why multicd.sh was breaking, or rather the sysrcd plugin.  

Please, for the sake of new users especially, like me please take 1 minute to update the doc with what is now a single typo!

> [538b2e3](https://github.com/IsaacSchemm/MultiCD/commit/538b2e38cb0d17924567301c64746820c3643c54) should fix SystemRescueCd. You'll have to use "sysresccd.iso" instead of "sysrcd.iso", though.
> 
> If it still doesn't work, just open a new issue.

Thanks, it works fine.
Pls update the "documentation" https://multicd.us/supported.html too.

_Originally posted by @dv8472 in https://github.com/IsaacSchemm/MultiCD/issues/68#issuecomment-469313628_

**Comment by IsaacSchemm** [comment]
Fixed, thanks. If you notice any other errors on that page, feel free to file a new issue.
